DROP TABLE IF EXISTS PARTICIPER;
DROP TABLE IF EXISTS ACCEDER;
DROP TABLE IF EXISTS COMPETITION;
DROP TABLE IF EXISTS CRENEAU;
DROP TABLE IF EXISTS ENCADRANT;
DROP TABLE IF EXISTS ADHERENT;
DROP TABLE IF EXISTS GROUPE;
DROP TABLE IF EXISTS UTILISATEUR;


CREATE TABLE UTILISATEUR (
`ID_UTILISATEUR` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
`NOM` VARCHAR(30) NOT NULL,
`PRENOM` VARCHAR(30) NOT NULL,
`MAIL` VARCHAR(100) NOT NULL,
`NUM_TEL` VARCHAR(12) NOT NULL,
`ADMINISTRATEUR` TINYINT(1) NOT NULL DEFAULT '0',
CONSTRAINT PK_UTILISATEUR PRIMARY KEY(ID_UTILISATEUR),
CONSTRAINT UNIQUE_MAIL UNIQUE(MAIL)
);

CREATE TABLE GROUPE (
`ID_GROUPE` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
`NOM` VARCHAR(30) NOT NULL,
CONSTRAINT PK_GROUPE PRIMARY KEY(ID_GROUPE)
);

CREATE TABLE ADHERENT (
`ID_ADHERENT` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
`NOM` VARCHAR(30) NOT NULL,
`PRENOM` VARCHAR(30) NOT NULL,
`DATE_NAISSANCE` DATE NOT NULL,
`NUM_LICENCE` INT(6),
`EN_REGLE` TINYINT(1) NOT NULL DEFAULT '0',
`ID_UTILISATEUR` INT(9) UNSIGNED NOT NULL,
`ID_GROUPE` INT(9) UNSIGNED,
CONSTRAINT PK_ADHERENT PRIMARY KEY(ID_ADHERENT),
CONSTRAINT FK_ADHERENT_UTILISATEUR FOREIGN KEY(ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR),
CONSTRAINT FK_ADHERENT_GROUPE FOREIGN KEY(ID_GROUPE) REFERENCES GROUPE(ID_GROUPE)
);

CREATE TABLE ENCADRANT (
`ID_ENCADRANT` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
`NOM` VARCHAR(30) NOT NULL,
`PRENOM` VARCHAR(30) NOT NULL,
`MAIL` VARCHAR(100) NOT NULL,
`NUM_TEL` VARCHAR(12) NOT NULL,
CONSTRAINT PK_ENCADRANT PRIMARY KEY(ID_ENCADRANT)
);

CREATE TABLE CRENEAU (
`ID_CRENEAU` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
`ID_ENCADRANT` INT(9) UNSIGNED NOT NULL,
`ID_GROUPE` INT(9) UNSIGNED NOT NULL,
CONSTRAINT PK_CRENEAU PRIMARY KEY(ID_CRENEAU),
CONSTRAINT FK_CRENEAU_GROUPE FOREIGN KEY(ID_GROUPE) REFERENCES GROUPE(ID_GROUPE),
CONSTRAINT FK_CRENEAU_ENCADRANT FOREIGN KEY(ID_ENCADRANT) REFERENCES ENCADRANT(ID_ENCADRANT)
);

CREATE TABLE COMPETITION (
`ID_COMPETITION` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
`NOM` VARCHAR(50) NOT NULL,
CONSTRAINT PK_COMPETITION PRIMARY KEY(ID_COMPETITION)
);

CREATE TABLE ACCEDER (
`ID_COMPETITION` INT(9) UNSIGNED NOT NULL,
`ID_ADHERENT` INT(9) UNSIGNED NOT NULL,
CONSTRAINT FK_ACCEDER_COMPETITION FOREIGN KEY(ID_COMPETITION) REFERENCES COMPETITION(ID_COMPETITION),
CONSTRAINT FK_ACCEDER_ADHERENT FOREIGN KEY(ID_ADHERENT) REFERENCES ADHERENT(ID_ADHERENT)
);

CREATE TABLE PARTICIPER (
`ID_COMPETITION` INT(9) UNSIGNED NOT NULL,
`ID_ADHERENT` INT(9) UNSIGNED NOT NULL,
CONSTRAINT FK_PARTICIPER_COMPETITION FOREIGN KEY(ID_COMPETITION) REFERENCES COMPETITION(ID_COMPETITION),
CONSTRAINT FK_PARTICIPER_ADHERENT FOREIGN KEY(ID_ADHERENT) REFERENCES ADHERENT(ID_ADHERENT)
);
