DROP TABLE IF EXISTS PROPOSITION;
DROP TABLE IF EXISTS CRENEAU;
DROP TABLE IF EXISTS ADHERENT;
DROP TABLE IF EXISTS GROUPE;
DROP TABLE IF EXISTS UTILISATEUR;

CREATE TABLE UTILISATEUR (
`ID_UTILISATEUR` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
`NOM` VARCHAR(30) NOT NULL,
`PRENOM` VARCHAR(30) NOT NULL,
`EMAIL` VARCHAR(100) NOT NULL,
`MOTDEPASSE` VARCHAR(64) NOT NULL,
`ADMINISTRATEUR` TINYINT(1) NOT NULL DEFAULT '0',
CONSTRAINT PK_UTILISATEUR PRIMARY KEY(ID_UTILISATEUR),
CONSTRAINT UNIQUE_MAIL UNIQUE(EMAIL)
);

CREATE TABLE GROUPE (
`ID_GROUPE` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
`NOM` VARCHAR(30) NOT NULL,
`DESCRIPTION` VARCHAR(200),
CONSTRAINT PK_GROUPE PRIMARY KEY(ID_GROUPE)
);

CREATE TABLE ADHERENT (
`ID_ADHERENT` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
`NOM` VARCHAR(30) NOT NULL,
`PRENOM` VARCHAR(30) NOT NULL,
`DATE_NAISSANCE` DATE NOT NULL,
`NUM_LICENCE` INT(6),
`EN_REGLE` TINYINT(1) NOT NULL DEFAULT '0',
`ID_UTILISATEUR` INT(9) UNSIGNED NOT NULL,
`ID_GROUPE` INT(9) UNSIGNED,
`EMAIL` VARCHAR(100) NOT NULL,
`TELEPHONE` VARCHAR(10) NOT NULL,
CONSTRAINT PK_ADHERENT PRIMARY KEY(ID_ADHERENT),
CONSTRAINT FK_ADHERENT_UTILISATEUR FOREIGN KEY(ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR),
CONSTRAINT FK_ADHERENT_GROUPE FOREIGN KEY(ID_GROUPE) REFERENCES GROUPE(ID_GROUPE)
);

CREATE TABLE CRENEAU (
`ID_CRENEAU` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
`HEURE_DEBUT` VARCHAR(5) NOT NULL,
`HEURE_FIN` VARCHAR(5) NOT NULL,
`JOUR` VARCHAR(8) NOT NULL,
`ENCADRANT` VARCHAR(50),
`ID_GROUPE` INT(9) UNSIGNED,
CONSTRAINT PK_CRENEAU PRIMARY KEY(ID_CRENEAU),
CONSTRAINT FK_CRENEAU_GROUPE FOREIGN KEY(ID_GROUPE) REFERENCES GROUPE(ID_GROUPE)
);

CREATE TABLE PROPOSITION (
`ID_PROPOSITION` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
`ID_GROUPE` INT(9) UNSIGNED NOT NULL,
`ID_ADHERENT` INT(9) UNSIGNED NOT NULL,
CONSTRAINT PK_PROPOSITION PRIMARY KEY(ID_PROPOSITION),
CONSTRAINT FK_PROPOSITION_GROUPE FOREIGN KEY(ID_GROUPE) REFERENCES GROUPE(ID_GROUPE),
CONSTRAINT FK_PROPOSITION_ADHERENT FOREIGN KEY(ID_ADHERENT) REFERENCES ADHERENT(ID_ADHERENT)
);

